### ISSUE TITLE
blueprint to goraml to generated client

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/howto_api#1]
- get blueprint spec from zerotier
- convert to goraml
- goraml to client
- test the client

**Comment by despiegk** [comment]
create example & proper documentation around it

**Comment by zaibon** [comment]
Didn't find any valid converter from blueprint to raml.

For the rest, everything is explained in the [README.md](https://github.com/zero-os/zerotier_client/blob/master/README.md) of the [zerotier_client repository](https://github.com/zero-os/zerotier_client)

**Comment by despiegk** [comment]
I want to use apiblueprint because its so much easier and there are many people who use this today, e.g. we have our Russian friends who want to help us to write specs

we can decide to write our own, I am sure its not that hard

**Comment by despiegk** [comment]
could be I have found a solution:

see https://github.com/Jumpscale/howto_api/tree/master/api%20blueprint

examples are there

**Comment by zaibon** [comment]
>I want to use apiblueprint because its so much easier and there are many people who use this today,

All our api description are in raml. This feels like we are changing complete direction again. Why instead not having a raml to api blueprint converted. Everyone in the company learned how to use raml already.
